### ISSUE TITLE
Error loading plugin:

### ISSUE THREAD

**Issue by jszzang** [intelsdi-x/snap-plugin-collector-intel-dcm-platform#7]
**Snap version** (use `snapctl -v`): 1.2.0

**Environment**:
- **Cloud provider or hardware configuration**: E5-2690 2socket x86 server 
- **OS** (e.g. from /etc/os-release):CentOS release 6.8 (Final)
- **Kernel** (e.g. `uname -a`):Linux wocp24 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Relevant tools** (e.g. plugins used with Snap): snap-plugin-collector-intel-dcm-platform
- **Others** (e.g. deploying with Ansible):

**What happened**:
cannot load the plugin 
#command to load plugin 
$ snaptel plugin load snap-plugin-collector-intel-dcm-platform
#Output
Error loading plugin:
unexpected EOF

$ cat /var/log/snap/snapteld.log
time="2017-04-14T17:36:32+09:00" level=error msg="error in getting metric types" _block=load-plugin _module=control-plugin-mgr error="unexpected EOF" plugin-type=collector
time="2017-04-14T17:36:32+09:00" level=error msg="unexpected EOF" _module="_mgmt-rest-v1"

**What you expected to happen**:
successfully load the plugin and read ipmi sensor values 

**Steps to reproduce it** (as minimally and precisely as possible):

1.  build the source 
2.  run $ snaptel plugin load snap-plugin-collector-intel-dcm-platform

**Anything else do we need to know** (e.g. issue happens only occasionally):

**Comment by IzabellaRaulin** [comment]
Hello @jszzang, I would like to confirm the way how you tried to load this plugin. Please, try load this plugin once again with these steps:

0. Pre-step:
- **ipmitool is installed** on your machine:
  Please check if ipmitool is available os your machine. If not, please install it by `yum install ipmitool` or using `wget`. FYI, I verify the plugin works correctly with ipmitool version 1.8.12

- **required ipmi modules are loaded** 
  Please check if the following modules are loaded: `ipmi_msghandler`, `ipmi_devintf ` and `ipmi_si`.
   If not, please load it: `modprobe  ipmi_msghandler` (and the same action for the next two).

1. Prepare config.json:
```json
{
    "control" : {
	"plugins": {
            "collector": {
                "intel-dcm-platform": {
                    "all": {
                        "protocol": "node_manager",
			 "mode": "legacy_inband",
                        "channel": "0x06",
                        "slave": "0x2C"
                    }
                }
            }
        }
    }
}
```
Read more about configuration options in [Configuration and usage section](https://github.com/intelsdi-x/snap-plugin-collector-intel-dcm-platform#configuration-and-usage)

2. Run snapteld with `--config` flag to provide the  path to config.json
```
$ snapteld -l 1- t 0 --config config.json
```

3. Load _intel-dcm-platform_ plugin and if exposed metrics are as you expected:
```
$ snaptel plugin load snap-plugin-collector-intel-dcm-platformel
$ snaptel metric list
```

Let me know if the plugin loads successfully on your machine. If some errors still occur, please provide your config file and logs (if there are any new ones).

**Comment by jszzang** [comment]
Hi @IzabellaRaulin  First off, thank you very much for your very kind explanations.  
I could load the plugin by using config file you mentioned.  
As a novice user, it would be great if you could explain about what the channel & slave means.  :)

After loading the plugin, I ran the metric list. 
`$snaptel metric list`
As you can see below, my server only has limited number of lists. 
```
[jszzang@test24 snap]$ snaptel metric list
NAMESPACE                                        VERSIONS
/intel/dcm/health/battery                        1
/intel/dcm/health/fan                            1
/intel/dcm/health/memory                         1
/intel/dcm/health/powersupply                    1
/intel/dcm/health/processor                      1
/intel/dcm/health/storage                        1
/intel/dcm/health/temperature                    1
/intel/dcm/health/voltage                        1
/intel/dcm/inventory/bmc_mac                     1
/intel/dcm/inventory/firmware_version            1
/intel/dcm/inventory/product_manufacturer        1
/intel/dcm/inventory/product_name                1
/intel/dcm/inventory/product_serial              1
```
I could watch an item in /intel/dcm/inventory/* list, but if I add any /intel/dcm/health/* item, I getting an errors like below and watch stops with [task-disabled] message. 
 
```
ERRO[2017-04-16T17:56:47+09:00] error selecting                               _module=control-routing block=select error=could not select a plugin strategy=least-recently-used
DEBU[2017-04-16T17:56:47+09:00] collector run completed                       _module=scheduler-job block=run job-type=collector metric-count=0
ERRO[2017-04-16T17:56:47+09:00] collector run error                           _module=scheduler-job block=run error=could not select a plugin job-type=collector
WARN[2017-04-16T17:56:47+09:00] Task failed                                   _block=spin _module=scheduler-task consecutive failure limit=10 consecutive failures=10 error=could not select a plugin task-id=f81b2da2-abc6-49f4-a617-7c61b11c7f3e task-name=Task-f81b2da2-abc6-49f4-a617-7c61b11c7f3e
ERRO[2017-04-16T17:56:47+09:00] Task disabled due to consecutive failures     _block=spin _module=scheduler-task consecutive failures=10 error=could not select a plugin task-id=f81b2da2-abc6-49f4-a617-7c61b11c7f3e task-name=Task-f81b2da2-abc6-49f4-a617-7c61b11c7f3e
DEBU[2017-04-16T17:56:47+09:00] event received                                _block=handle-events _module=scheduler-events disabled-reason=Task disabled with error: could not select a plugin event-namespace=Scheduler.TaskDisabled task-id=f81b2da2-abc6-49f4-a617-7c61b11c7f3e

```

**Comment by IzabellaRaulin** [comment]
Hello @jszzang, It's great that the plugin was loaded successfully with provided config. 

1. According to config params:
> As a novice user, it would be great if you could explain what the channel & slave means.

Those two parameters are for configuring IPMI communication:
- **channel** - defines communication channel address to send IPMI requests to,
- **slave** - defines driver target slave number to send IPMI requests to.

Their values are determined by platform. Authors of the plugin might answer your question more thoroughly.

2. According to collecting health metrics:

> I could watch an item in /intel/dcm/inventory/* list, but if I add any /intel/dcm/health/* item, I getting an errors like below and watch stops with [task-disabled] message.
  
This plugin is in Alpha state and there is a point _More health info support_ on the current [roadmap](https://github.com/intelsdi-x/snap-plugin-collector-intel-dcm-platform#roadmap).  **I would like to confirm with plugin authors if retrieving health metrics is expected to work or it is still in progress.**  

@XinDongIntel, @dancyding, @WangJialei-A - can I ask you to provide more information about set values of `channel` and `slave` (point1)? Do you have any idea why requesting health metrics causes task failures (point 2)?

**Comment by jszzang** [comment]
Hi @IzabellaRaulin and all. I've tested with various options - protocol(dcmi, ipmi, node-manager), mode (legacy_inband, legacy_inband_openipmi), channel (0x00, 0x06, 0xf), slave (0x2c, 0x00) . However, I still couldn't get metrics except inventory. 

I'm going to develop hardware management system which collects hardware and system data, such as os level data, inventory, power, and fan. One of the most important goals of my project is to reduce vendor dependencies. (We have HP, Dell, Wiwynn, IBM servers)

As you all know, each vendor's ipmi data has different format and hard to collect, manage, and monitor. I found that snap is designed with similar principles that I wanted, and really want to use snap framework for my project. Therefore, we are willing to contribute this project. 

Here are some questions and I'll also provide more detailed configurations and steps that I took. 
**Questions**
1. Are there any hardware vendor dependencies with this plugin? If yes, can you provide what to look for and what to modify? 
2. It looks like that the plugin uses ipmitool to retrieve h/w data. What channel and slave address should I use? 

**How I ran the plugin**
 1. snap-config.json 
```
{
    "log_level":1,
    "log_path":"/var/log/snap",
    "log_truncate":false,
    "log_colors":true,
    "gomaxprocs":2,
    "control":{
        "auto_discover_path":"/opt/snap/plugins:/opt/snap/tasks",
        "max_plugin_restarts":100,
        "listen_addr":"127.0.0.0",
        "listen_port":8082,
        "max_running_plugins":3,
        "plugin_load_timeout":20,
        "temp_dir_path":"/tmp",
        "plugin_trust_level":0,
        "plugins":{
            "collector":{
                "intel-dcm-platform": {
                   "all": {
                        "protocol": "dcmi",
                        "mode": "legacy_inband",
                        "channel": "0x00",
                        "slave": "0x00"
                        }
                }

            },
        },
    },
    "scheduler":{
        "work_manager_queue_size":25,
        "work_manager_pool_size":4
    }
}

```
2. Run snapteld 
```
[jszzang@wocp24 snap]$ snaptel -v
snaptel version 1.2.0
[jszzang@wocp24 snap]$ snaptel -l 1 -t 0 snap-config.json
```

3. Load plugin 
```
[jszzang@wocp24 snap]$ snaptel plugin list
NAME                     VERSION         TYPE            SIGNED          STATUS          LOADED TIME
cpu                      6               collector       false           loaded          Wed, 19 Apr 2017 10:16:34 KST
intel-dcm-platform       1               collector       false           loaded          Wed, 19 Apr 2017 10:16:34 KST
file                     2               publisher       false           loaded          Wed, 19 Apr 2017 10:16:34 KST
```

4. Task file 
```
[jszzang@wocp24 snap]$ cat tasks/task_dcm_file2.json
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "5s"
    },
    "workflow": {
        "collect": {
            "metrics": {
                        "/intel/dcm/power/system/avg":{},
                        "/intel/dcm/inventory/firmware_version":{},
                        "/intel/dcm/health/powersupply":{},
                        "/intel/dcm/health/fan":{},
                        "/intel/dcm/health/processor":{}
            },
            "config": {
            },
            "process": null,
            "publish": [
                {
                    "plugin_name": "file",
                    "plugin_version": 2,
                    "config": {
                        "file": "/tmp/published_dcminfo"
                    }
                }
            ]
        }
    }
}
```

5. Load and Run task 
```
[jszzang@wocp24 snap]$ snaptel plugin list
NAME                     VERSION         TYPE            SIGNED          STATUS      LOADED TIME
cpu                      6               collector       false           loaded      Wed, 19 Apr 2017 11:08:31 KST
intel-dcm-platform       1               collector       false           loaded      Wed, 19 Apr 2017 11:08:31 KST
file                     2               publisher       false           loaded      Wed, 19 Apr 2017 11:08:32 KST
[jszzang@wocp24 snap]$ snaptel task create -t tasks/task_dcm_file2.json
Using task manifest to create task
Task created
ID: 56d02842-55df-4726-b616-883b1528bf62
Name: Task-56d02842-55df-4726-b616-883b1528bf62
State: Running

```

6. Task list and watch 
```
[jszzang@wocp24 snap]$ snaptel task list
ID                                       NAME                                        STATE            HIT     MISS    FAIL    CREATED                 LAST FAILURE
56d02842-55df-4726-b616-883b1528bf62     Task-56d02842-55df-4726-b616-883b1528bf62   Running          4       1       3       11:08AM 4-19-2017       connection is shut down
```
```
[jszzang@wocp24 snap]$ snaptel task watch 56d02842-55df-4726-b616-883b1528bf62
Watching Task (56d02842-55df-4726-b616-883b1528bf62):
[task-disabled]
```

7.  $ cat /var/log/snap/snapteld.log
Please see attached file. 
[snapteld.log.txt](https://github.com/intelsdi-x/snap-plugin-collector-intel-dcm-platform/files/931569/snapteld.log.txt)

**Version Info**
```
[jszzang@wocp24 snap]$ uname -a
Linux wocp24 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
```
[jszzang@wocp24 snap]$ snaptel -v
snaptel version 1.2.0
```
```
[jszzang@wocp24 snap]$ go version
go version go1.8.1 linux/amd64
```
```
[jszzang@wocp24 snap]$ cat /etc/centos-release
CentOS release 6.8 (Final)
```

Thank you!

**Comment by IzabellaRaulin** [comment]
Hello @jszzang. Thank you once again for reporting the issue and providing all details which were very helpful. It has been resolved by https://github.com/intelsdi-x/snap-plugin-collector-intel-dcm-platform/issues/10.  It would be great if you try with the latest version to confirm that. If the issue still occurs on your system, do not hesitate to reopen this GH issue and let me know. Thank You.

**Comment by jszzang** [comment]
Hi ! @IzabellaRaulin I tested with the updates and it works well! Thank you very much. 
BTW, I have another question. 

I’d like to collect H/W information through OOB (out of band) network. (ex. ipmi)
The intel-dcm-platform plugin looks like it only can collect one host’s ipmi info at a time.

How can I collect multiple host’s ipmi information through OOB network?
It's hard to find a "HOWTOs" for my needs. 

And I cannot not get a full ipmi information correctly – like sdr information.
If possible, could you guide us how to modify the plugin so that I can collect all the sdr information in general server?
 
Thank you!

**Comment by WangJialei-A** [comment]
Hello @jszzang. Thank you for your feedback. How many hosts do you want to get monitored? It is a time consuming work to communicate with multiple servers. Here is a workaround solution to handle just three or five servers: 
1. Launch several snapteld services listening on different ports and reading different configurations.
2. Use snaptel to load the plugins on the snapteld services with the ports.

Thank you.

**Comment by jszzang** [comment]
Hi @WangJialei-A,
I'm developing hardware monitoring system for our servers and want to monitor those servers both in-band and OOB network using IPMI/DCMI. So the number of servers to be monitored will be few hundreds server at first, and it can be extended to few thousands of servers. 

If this plugin is not designed for collecting many server's information through OOB network, do you think that it is possible to develop the plugin for SNAP?
